### ISSUE TITLE
New dataset

### ISSUE THREAD

**Issue by onurbbruno** [hust-linyi/CAT-Net#13]
Thank you for contribution!

I was wondering if the code is expandable to other (cardiac) medical dataset. (In particular I'm finding trouble to set up the supervoxel directory).

Thank you in advance.

**Comment by hust-linyi** [comment]
Please refer to link below for the data pre-processing:
https://github.com/cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation
