### ISSUE TITLE
This attribute is missing “high_avg_pool” in the fewshot.py file

### ISSUE THREAD

**Issue by WangBingJian233** [hust-linyi/CAT-Net#3]
Hello author, thank you very much for your excellent work.
In the process of replicating the code, I found that this attribute “high_avg_pool” missing from the fewshot.py file. And the part that deals with the Abd-CT dataset is missing from the code. Can you provide the code?

![image](https://github.com/hust-linyi/CAT-Net/assets/59432372/779bd5aa-bcbd-44ba-a9b0-0f714661ae54)

**Comment by Julesaiyy** [comment]
I have the same question and look forward to the author's answer.

**Comment by WangBingJian233** [comment]
I do two things with this part: 1. Remove self.high_avg_pool from the code, i.e. : q = query_feat.flatten(2).transpose(-2, -1). 2. Add self.high_avg_pool = nn.AdaptiveAvgPool1d(self.encoder.output_dim // 2). However, my reproduction results are not up to what is described in the paper. I am looking forward to your operation and the author's explanation.
