### ISSUE TITLE
There is a bug in the attention mechanism in the code

### ISSUE THREAD

**Issue by WangBingJian233** [hust-linyi/CAT-Net#6]
Hello author, there are problems in the self-attention mechanism and cross-attention mechanism in the code you updated, the MLP layer and the normalization layer are missing, and the gradient descent is obviously wrong during training. Please modify the code

**Comment by CYF2000127** [comment]
Thanks for your attention! We have fixed this bug and the bug that you mentioned before, you can check now! Thanks!
