### ISSUE TITLE
Setting

### ISSUE THREAD

**Issue by lsp-stack** [hust-linyi/CAT-Net#7]
how to change config parameters to decide whether we train under setting 1 or setting 2?

**Comment by CYF2000127** [comment]
you should manually modify the train.sh, add supp_idx = [1] or [2] after path.log_dir=$LOGDIR to change the support image in each fold  for the setting 2

**Comment by lsp-stack** [comment]
I still don't understand why I found the use of `args['supp_idx']` in the class `TestDataset` instead of the class `TrainDataset`. Are you sure we only need to modify `train.sh` for setting `ii`?Is there anything else that needs to be modified?And how should I set the setting I?Can you provide more detailed instructions? Thank you very much for your help.
